import type { Metadata } from "next";
import "./globals.css";
import firebase from "firebase/compat/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window !== "undefined") {
    window.addEventListener("beforeunload", () => {
      console.log("Disconnecting from Firebase");
      firebase.database().goOffline();
    });
  }
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
